version: '3'

services:
  app:
    container_name: "fastapi-backend-app"
    image: fastapi-backend-app
    environment:
      - MONGO_HOST=mongo_db
      - MONGO_PORT=27017
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mongo_db
    networks:
      - my-network

  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    networks:
      - my-network

  mongo_import:
    image: mongo
    build:
      context: ./import
      dockerfile: Dockerfile
    volumes:
      - ./import/hotels.json:/data/data.json
    depends_on:
      - mongo_db
    networks:
      - my-network

networks:
  my-network:
